service: zoho-ats-integration

frameworkVersion: "3"

useDotenv: true   

provider:
  name: aws
  runtime: python3.10
  environment:
    ZOHO_CLIENT_ID: ${env:ZOHO_CLIENT_ID}
    ZOHO_CLIENT_SECRET: ${env:ZOHO_CLIENT_SECRET}
    ZOHO_REFRESH_TOKEN: ${env:ZOHO_REFRESH_TOKEN}
    ZOHO_BASE_URL: ${env:ZOHO_BASE_URL}

functions:
  getJobs:
    handler: handler.get_jobs
    events:
      - http:
          path: jobs
          method: get

  createCandidate:
    handler: handler.create_candidate
    events:
      - http:
          path: candidates
          method: post

  getApplications:
    handler: handler.get_applications
    events:
      - http:
          path: applications
          method: get

plugins:
  - serverless-offline
